# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'already_running.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlreadyRunning(object):
    def setupUi(self, AlreadyRunning):
        AlreadyRunning.setObjectName("AlreadyRunning")
        AlreadyRunning.resize(206, 98)
        AlreadyRunning.setMinimumSize(QtCore.QSize(206, 98))
        AlreadyRunning.setMaximumSize(QtCore.QSize(206, 98))
        self.gridLayout = QtWidgets.QGridLayout(AlreadyRunning)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(AlreadyRunning)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(AlreadyRunning)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(AlreadyRunning)
        self.buttonBox.rejected.connect(AlreadyRunning.reject)
        self.buttonBox.accepted.connect(AlreadyRunning.accept)
        QtCore.QMetaObject.connectSlotsByName(AlreadyRunning)

    def retranslateUi(self, AlreadyRunning):
        _translate = QtCore.QCoreApplication.translate
        AlreadyRunning.setWindowTitle(_translate("AlreadyRunning", "Already Running"))
        self.label.setText(_translate("AlreadyRunning", "WARP already running!"))

